### ISSUE TITLE
TrueCrypt requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0

### ISSUE THREAD

**Issue by Que2** [stefansundin/truecrypt-mac#1]
Hello I am trying to run your updated build of TrueCrypt on OS 10.13 but found that is immediately crashes on load and gives me the error message below: 

Dyld Error Message:
  Library not loaded: /usr/local/opt/xz/lib/liblzma.5.dylib
  Referenced from: /Applications/TrueCrypt64.app/Contents/MacOS/TrueCrypt
  Reason: Incompatible library version: TrueCrypt requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0

I tried to find out what library this is so I could download this and have your application work.  But it looks like this has something to do with brew... but I never installed brew nor do I have a existing file at that location that is of the 6.0 version.  Unless this is somewhere in the system libraries.  

It looks like it may be fix to install brew but, I do not want to install brew and just want the library but I have been unable to locate this on the internet other than instructions via brew "brew install xz".

I have the latest version of OSX Fuse so I am at a loss why I can not get this to run so I am reaching out.  I am trying to move from the 32 bit version of this to a 64 bit to go to Catalina.

I hope you check the issues... it has seemed dead for awhile...

**Comment by stefansundin** [comment]
The library was probably not statically linked when I compiled it. I will have to try again. Thanks for reporting the issue.

What do you mean by "it has seemed dead for awhile"?

**Comment by Que2** [comment]
Stefansundin, you put this out in 2019 and no comments and no issues.  It was only hope that this project was not abandoned.   You wrote your comments so long ago, that is what I meant.  Thanks so much for taking a look at this for me!

**Comment by Que2** [comment]
Stefansundin, how are are things going.  Is there another way that I can obtain this library short of a re-compile?

**Comment by stefansundin** [comment]
Sorry, I've been meaning to set up a VM so that I can try this on a fresh mac installation, but I just haven't had time for it just yet.

**Comment by Que2** [comment]
I did locate a binary version of the library but since the original is located /usr/lib it is protected by SIP so it would be hard to replace.
https://apple.stackexchange.com/questions/208764/cant-write-to-usr-lib

I am not a coding expert but it looks like most people like you said link this as an external bundle, which is seen as a Frameworks directory in an app bundle:
http://lessons.livecode.com/m/4071/l/15029-linking-an-osx-external-bundle-with-a-dylib-library

========================
I am running macOS 10.13.6.
Below is what I see when I run the otool -L against the original library and the version 8.4 of the same library.

HOST:/[REDACTED]$ otool -L liblzma.5.dylib
liblzma.5.dylib:
	/usr/local/lib/liblzma.5.dylib (compatibility version 8.0.0, current version 8.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)

HOST:/[REDACTED]$ cd /usr/lib
HOST::lib [REDACTED]$ otool -L liblzma.5.dylib
liblzma.5.dylib:
	/usr/lib/liblzma.5.dylib (compatibility version 6.0.0, current version 6.3.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)

**Comment by stefansundin** [comment]
I finally got the time to work on this. Even though I was not able to reproduce your exact problem (the file `/usr/lib/liblzma.5.dylib` was present on all of the machines I was able to check), I was able to compile wxWidgets without liblzma by [adding `--without-liblzma` to the wxWidgets options](https://github.com/stefansundin/truecrypt-mac/commit/04bae36c7943131c041bda396f9d73f537d293cf#diff-b67911656ef5d18c4ae36cb6741b7965R261). Check out the release here: https://github.com/stefansundin/truecrypt-mac/releases/tag/v5

Here's the new otool output:

```
$ otool -L /Applications/TrueCrypt.app/Contents/MacOS/TrueCrypt
/Applications/TrueCrypt.app/Contents/MacOS/TrueCrypt:
	/usr/local/lib/libosxfuse.2.dylib (compatibility version 12.0.0, current version 12.7.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 162.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 23.0.0)
	/System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox (compatibility version 1.0.0, current version 1000.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 59306.101.1)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1894.40.150)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 52.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1675.129.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1355.13.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1069.22.0)
	/System/Library/Frameworks/CoreText.framework/Versions/A/CoreText (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1675.129.0)
	/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

It is interesting to compare that against the official 7.1a binary (multiarch so both 32-bit and powerpc shows up):
```
TrueCrypt (architecture i386):
	/usr/local/lib/libfuse.2.dylib (compatibility version 10.0.0, current version 10.7.3)
	/usr/lib/libiconv.2.dylib (compatibility version 5.0.0, current version 5.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 128.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 11.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 88.3.11)
	/System/Library/Frameworks/QuickTime.framework/Versions/A/QuickTime (compatibility version 1.0.0, current version 1290.0.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.4.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 18.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 368.35.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 22.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 567.42.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 824.48.0)

TrueCrypt (architecture ppc):
	/usr/local/lib/libfuse.2.dylib (compatibility version 10.0.0, current version 10.7.3)
	/usr/lib/libiconv.2.dylib (compatibility version 5.0.0, current version 5.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 128.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 11.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 88.3.11)
	/System/Library/Frameworks/QuickTime.framework/Versions/A/QuickTime (compatibility version 1.0.0, current version 1290.0.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.4.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 18.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 368.35.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 22.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 567.42.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 824.48.0)
```

Sorting and removing common libraries, this is basically the diff:
```
/Applications/TrueCrypt.app/Contents/MacOS/TrueCrypt:
	/System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox (compatibility version 1.0.0, current version 1000.0.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1355.13.0)
	/System/Library/Frameworks/CoreText.framework/Versions/A/CoreText (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 59306.101.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/local/lib/libosxfuse.2.dylib (compatibility version 12.0.0, current version 12.7.0)

TrueCrypt (architecture i386):
	/System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/QuickTime.framework/Versions/A/QuickTime (compatibility version 1.0.0, current version 1290.0.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.4.0)
	/usr/local/lib/libfuse.2.dylib (compatibility version 10.0.0, current version 10.7.3)
```

I assume this is because of newer Xcode and changes in wxWidgets, but that's mostly a guess. It would be interesting to see if we could remove more junk somehow. Even though I added `--without-opengl`, apparently `OpenGL.framework` is still linked.

Anyway, let me know if the new version works well for you.

**Comment by Que2** [comment]
This version works great!  This solves all of my issues.  Please let me know if you want me to test anymore builds.  This seems rock solid so far for me.

**Comment by stefansundin** [comment]
Great to hear. Let me know if you have any other issues. I also opened #2 and #3 to help people build and install the program since it is not super simple.

I think I will try it with the Big Sur beta soon to see if it works or need more changes. Some other things I want to work on some day is try to get it to work with wxWidgets 3.1.3 and 3.1.4. The [changelog for 3.1.4](https://raw.githubusercontent.com/wxWidgets/wxWidgets/v3.1.4/docs/changes.txt) says "Add support for macOS 11", so it will be interesting to see if that will be necessary.

**Comment by Que2** [comment]
Stefan, if you are looking at Big Sur...  I wonder are you thinking about the new dual binary and actually compiling this for ARM/x64?

**Comment by stefansundin** [comment]
Probably not. I am not sure if I will ever own that hardware.

**Comment by stefansundin** [comment]
Big Sur seems to work mostly fine. I just had a minor osxfuse quirk. I opened #4 for discussion.
